#!/usr/bin/env python
import os
import sys

# Add current directory for methods import (SCons sets os.getcwd() to SConstruct dir)
sys.path.insert(0, os.getcwd())
from methods import print_error

libname = "nexus_vertex_painter"
# Output compiled libraries to addon bin/ folder only - no source in Godot project
addon_bin = os.path.join(os.getcwd(), "..", "game", "addons", "nexus_vertex_painter", "bin")

localEnv = Environment(tools=["default"], PLATFORM="")

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("godot-cpp") and os.listdir("godot-cpp")):
    print_error("""godot-cpp is not available. Clone it with:

 cd src
 git clone -b 4.2 https://github.com/godotengine/godot-cpp godot-cpp
 cd godot-cpp && git submodule update --init --recursive && cd ..""")
    sys.exit(1)

env = SConscript("godot-cpp/SConstruct", {"env": env, "customs": customs})

# Sources are in current directory (src/)
env.Append(CPPPATH=["."])
sources = Glob("*.cpp")

# Editor plugin - include doc data if targeting editor (Godot 4.3+)
if env.get("target") in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData("gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
        sources.append(doc_data)
    except AttributeError:
        pass

suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
lib_filename = "{}{}{}{}".format(
    env.subst("$SHLIBPREFIX"), libname, suffix, env.subst("$SHLIBSUFFIX")
)

# Build to local bin/ first, then install to addon
library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

# Install compiled library to addon folder only
copy = env.Install("{}/{}/".format(addon_bin, env["platform"]), library)

Default(library, copy)
